apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nginx-test
  annotations:
    argocd/app-name: nginx-test
spec:
  type: service
  lifecycle: experimental
  owner: group:default/backend-admin
