apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nginx-service
  description: Nginx for FrontEnd Team
  annotations:
    # This must match the label 'backstage.io/kubernetes-id' in your K8s manifest
    backstage.io/kubernetes-id: nginx-service 
spec:
  type: service
  lifecycle: production
  owner: ragisreekanth@example.com
