apiVersion: scaffold.backstage.io/v1beta3
kind: Template
metadata:
  name: deploy-nginx-template
  title: Nginx Deployer
spec:
  parameters:
    - title: WebApps Proxy
      properties:
        repoName:
          title: backstage-templates
          type: string
        namespace:
          title: nginx-argo-bs
          type: string
          default: default

  steps:
    - id: template
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton # Path to your Nginx manifests
        values:
          repoName: ${{ parameters.repoName }}
          namespace: ${{ parameters.namespace }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts: ['github.com']
        repoUrl: "://github.com{{ parameters.repoName }}&owner=your-org"

    - id: create-argocd
      name: Create Argo CD Application
      action: argocd:create-resources
      input:
        appName: ${{ parameters.repoName }}
        projectName: default
        namespace: ${{ parameters.namespace }}
        repoUrl: "https://github.com{{ parameters.repoName }}"
        path: "default/"
